### ISSUE TITLE
Make a MELPA recipe

### ISSUE THREAD

**Issue by syl20bnr** [jcs-elpa/auto-highlight-symbol#1]
@gennad Hi Gennadiy,

auto-highlight-symbol is missing in MELPA repository which is a dependency of [EDTS](http://melpa.milkbox.net/#/edts) (see issue tjarvstrand/edts/issues/147).

Can you make a recipe for `ahs` in [MELPA](https://github.com/milkypostman/melpa) ?

Thank you,
syl20bnr

**Comment by jcs090218** [comment]
Close this issue now! :D
