### ISSUE TITLE
Same buffer in two windows, next/prev symbol issues

### ISSUE THREAD

**Issue by duianto** [jcs-elpa/auto-highlight-symbol#11]
The cursor jumps to the wrong location, when trying to navigate to the next symbol.
When the same buffer is open in two windows.

### Reproduction steps
- Open a new buffer: `C-x b` `test` `RET`
- Copy and paste:
```
If you would like to contribute to this project, you may either clone and make pull requests to this repository. Or you can clone the project and establish your own branch of this tool. Any methods are welcome!
```
The text is from the readme contribution section:
https://github.com/jcs-elpa/auto-highlight-symbol#contribution

- Move the cursor to the second word: `you`

- Split the frame into two windows: `C-x 2`
The inactive cursor in the bottom window (shown as a hollow rectangle),
is on the `y` in the second word `you`.

The active cursor (black rectangle) is in the top window.
- Move the active cursor to the fifth word `to`:
`C-s` `to` `RET`
- Enable ahs mode: `M-x auto-highlight-symbol-mode` `RET`
A most likely unrelated error message is shown (the jump issue has been encountered without the error message being shown, possibly when the major mode wasn't `fundamental-mode`):
```
Error running timer ‘ahs-idle-function’: (wrong-type-argument number-or-marker-p nil)
```
It's been reported in a separate issue:
Error running timer ‘ahs-idle-function’: (wrong-type-argument number-or-marker-p nil) #10

- Press `Alt Tab` to unfocus Emacs (switch to another application)
- Press `Alt Tab` again to focus Emacs.
Now the three instances of `to` are highlighted in the top window.
And the three instances of `you` are highlighted in the bottom window.

With the top window selected:
- Try to navigate to the next highlighted symbol: `M-right`

### Observed
The cursor jumps to the `o` in `clone` (fourth word after the comma).

### Expected
The cursor should have jumped to the second instance of `to` (seventh word).

### Notes
In the top window, move back the cursor to the fifth word `to`.

Keep navigating to the next symbol `M-right`.
The cursor jumps to three places:
The `o` in `clone` in the first sentence.
Between `the` and `project` in the second sentence
Then back to the starting location, after the fifth word `to`.

The orange highlight in the top window doesn't move,
while jumping to the next symbol.
Until the cursor is stopped on another word,
then the highlighted symbols update.

But the orange highlight in the bottom window,
jumps between each instance of the highlighted word `you`.

### A possible cause
It seems like the cursor in the top window is jumping forwards by the same amount of characters, as the distance between the bottom windows highlighted words.

For example in the top window:
From the end of the fifth word `to`,
to (but not including) the `o` in the word `clone`,
is 46 characters (including the leading space):
```
 contribute to this project, you may either cl
```

In the bottom window:
From the end of the second word `you`,
to the second instance of `you` (before the `y`),
is also 46 characters (including the leading space).
```
 would like to contribute to this project, you
```

The same behavior can be seen when, selecting the bottom window
and navigating to the next symbol.

The cursor in the bottom window jumps the same distance as between the instances of `you` in the top window.

And the orange highlight in the top window jumps between the instances of the word `to`.

### System info
auto-highlight-symbol-20210708.1057
GNU Emacs 27.2 (build 1, x86_64-w64-mingw32) of 2021-03-26
Windows 21H1

**Comment by jcs090218** [comment]
I have applied a fix to master branch. Can you try the latest version?

Thanks for reporting this issue to us!

**Comment by duianto** [comment]
It works as expected now.
`M-right` and `M-left` jumps to the next/prev symbol in the selected window.

Thanks
