### ISSUE TITLE
Turning the mode off should stop the ahs-idle-function

### ISSUE THREAD

**Issue by olejorgenb** [jcs-elpa/auto-highlight-symbol#4]
This is a very minor and "cosmetic" issue of course.

```
(define-minor-mode auto-highlight-symbol-mode
  "Toggle Auto Highlight Symbol Mode"
  :group 'auto-highlight-symbol
  :lighter ahs-mode-line
  (if auto-highlight-symbol-mode
      (ahs-init)
    (ahs-clear))) ; <---- does not stop/clear timer
```

**Comment by jcs090218** [comment]
Yes, you are right. Can you still produce this issue? I am not able to reproduce this issue for the current version.

Thanks!

**Comment by olejorgenb** [comment]
Sorry, don't have time to dig much into this right now, but from a quick skim of the code I can't see that `ahs-idle-timer` is ever stopped? Ie.: when turning off a mode I don't expect a timer to keep running. The timer function is of course very cheap so this is more about the principle I guess :)

```elisp
(define-minor-mode auto-highlight-symbol-mode
  "Toggle Auto Highlight Symbol Mode"
  :group 'auto-highlight-symbol
  :lighter ahs-mode-line
  (if auto-highlight-symbol-mode
      (ahs-init)
    (progn 
     (ahs-clear)
     (cancel-timer ahs-idle-timer)
     (setq ahs-idle-timer nil))))
```

I honestly don't remember why I noticed this in the first place :man_shrugging:

**Comment by jcs090218** [comment]
> When turning off a mode I don't expect a timer to keep running. The timer function is of course very cheap so this is more about the principle I guess :)

I agree with your point here! ;)

> I honestly don't remember why I noticed this in the first place

No worries! I am just not able to reproduce the issue. Anyway, I know there is timer running yet the package wouldn't do the highlighting after the minor mode has turned off.

**Comment by olejorgenb** [comment]
Ah, I think I see the confusion - the auto highlightning do **stop** when the mode is disabled, but the timer keep running. (there's a guard on the mode variable in the timer)

I verified that `ahs-idle-function` runs when the mode is off by adding a `(message "hello")` statement.

```
;; Version: 1.59
;; Package-Version: 20201018.1340
;; Package-Commit: 0982390f19fee3c05856b9e4e40056dce4c4020d
``

(This is using spacemacs though, which is known for fiddling just bit too much some time)

**Comment by olejorgenb** [comment]
Ups, I just realized that the mode variable is per buffer, while the timer is global, so it probably have to keep running. Sorry for the noise :)

**Comment by jcs090218** [comment]
No problem! Glad this issue is resolved! :)
