### ISSUE TITLE
New faces with a typo in the names

### ISSUE THREAD

**Issue by agzam** [jcs-elpa/auto-highlight-symbol#6]
Looks like the names of the faces introduced in: https://github.com/jcs-elpa/auto-highlight-symbol/commit/7d7d89aa16d4f09f18dac15a6f594ba5b1dba443
are mistyped. 

i.e., perhaps it should be `ahs-plugin-default-face` instead of: `ahs-plugin-defalt-face`

**Comment by jcs090218** [comment]
Ah, I guess the it was named with typo before I introduced another face `ahs-plugin-default-face-unfocused`. Fix with d9b83fa766078533ee712ca50cb49f0487b3a18a. Thanks! :)
