### ISSUE TITLE
install/update: void: ahs-focus-out and void ahs-focus-in

### ISSUE THREAD

**Issue by duianto** [jcs-elpa/auto-highlight-symbol#8]
After installing or updating: `auto-highlight-symbol`

When the Emacs frame loses/gains focus when switching to/from another application.

Then the messages buffer shows:
```
if: Symbol’s function definition is void: ahs-focus-out
if: Symbol’s function definition is void: ahs-focus-in
```

Restarting Emacs after the install/update fixes it.
But is it possible to handle it without having to restart?

System info
auto-highlight-symbol-20210705.1351
GNU Emacs 27.2 (build 1, x86_64-w64-mingw32) of 2021-03-26
Windows 21H1

**Comment by jcs090218** [comment]
Make sure you require auto-higlight-symbol before calling these functions. These functions aren't autoload.

**Comment by duianto** [comment]
The functions are called automatically when the Emacs frame is un/focused.
Before any ahs function has been called.

Maybe it should check that `auto-highlight-symbol-mode` is enabled, here:
https://github.com/jcs-elpa/auto-highlight-symbol/blob/e8809909565ec0184920eb4236709581a607fafe/auto-highlight-symbol.el#L1726-L1733

**Comment by jcs090218** [comment]
I have removed `eval-and-compile`. Would this work?

**Comment by duianto** [comment]
I don't know. I can check when melpa has the latest version.

**Comment by duianto** [comment]
I just updated to: `auto-highlight-symbol-20210708.1057`

The void messages do not appear anymore, when updating or installing from scratch:
- Updating:
`M-x package-list-packages`
when the `*Packages*` buffer opens, then the mode line shows: `Packages: Loading`
When it's done, if there's an update, then it shows a update available message,
and that one can press `U` (uppercase u) to mark them for update.
Pressing: `x` updates the package(s).
- Installing from scratch:
by closing Emacs, removing the contents of the `.emacs.d/elpa` directory,
start Emacs and install the package with: `M-x package-install`
When the `Install package:` prompt appears,
type: `auto-highlight-symbol` and press `RET`

Thanks
